spring:
  application:
    name: newspush
  datasource:
    url: jdbc:sqlite:app.db?journal_mode=WAL&busy_timeout=5000
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true

logging:
  level:
    com.newspush: DEBUG